name: ecommers_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8


#--------------- ./state management ----------------#
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true



#--------------- ./local assets ----------------#
assets:
  - assets/logos/
  - assets/icons/branch/
  - assets/images/



  #--------------- ./local Fonts ----------------#

fonts:
  - family: Poppins
    fonts:
      -assets:    